# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-02 06:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_porfolioimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PorfolioImage',
            new_name='PortfolioImage',
        ),
    ]
